### ISSUE TITLE
Collection not created

### ISSUE THREAD

**Issue by RY4GIT** [TUW-GEO/ismn#34]
Hello, I am using your package with environment.yml on miniconda

I followed the tutorial and created ismn_data instance, however, ismn_data does not contain collection 

Could you please help me with this problem? 

```
from ismn.interface import ISMN_Interface

# Enter the path to your ISMN data
path_to_ismn_data = "myfilepath/Data_separate_files_20000101_20200229_6817_FTVy_20210520"
ismn_data = ISMN_Interface(path_to_ismn_data, network=['SCAN', 'USCRN'])
```

**Comment by wpreimes** [comment]
Hi @RY4GIT,
thanks for reporting, we are still updating the docs for this, there is no "collection" anymore in `ISMN_Interface`. It should be possible to access the networks directly via their name (e.g. `ismn_data['SCAN']` to get the station data for SCAN). I will push another update soon.

**Comment by RY4GIT** [comment]
I see, thank you! 
By slicing ismn_data.metadata, I was able to access metadata. 

Do the functions iter_sensors and read_data work in a similar way with the current documentation?

**Comment by wpreimes** [comment]
Can you check what verion of the package you have installed? I assume the problem is that you have installed the package with pip (i.e `v0.4`), the current master branch version is not yet released on pypi, therefore the documentation does not match to your code. Either install the new package (from github or wait until we pushed it on pypi) or look at the old docs https://ismn.readthedocs.io/en/v0.4/

**Comment by wpreimes** [comment]
We have released the new version on pypi. Feel free to open another issue if you run into errors with this. Feedback is really welcome!

**Comment by RY4GIT** [comment]
I cannot thank you enough for your prompt response and update!!
I will install the updated version
